server:
  port: 8097
spring:
  profiles:
    active: local,alipay-sandbox,weixin-gzh
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      naming:
        implicit-strategy: com.fushun.framework.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: com.fushun.framework.jpa.hibernate.SpringPhysicalNamingStrategy
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  resources:
    add-mappings: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

logging:
  level:
    root: INFO
  path: log
  file:
    max-size: 10MB
    max-history: 30

pay:
  startWeb: true
  notifyUrl: http://www.ihaoshenghuo.com/pay/source/web_weixin_notice.php

