spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
app:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/bldsupermarket?serverTimezone=Asia/Shanghai&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    pool-size: 30
    driverClassName: com.mysql.cj.jdbc.Driver