server:
  port: 8097
spring:
  profiles:
    active: local,alipay-sandbox,weixin-gzh
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


logging:
  level:
    root: INFO
  path: log
  file:
    max-size: 10MB
    max-history: 1000