pay:
  weixin:
    gzh:
      key: 8934e7d15453e97507ef794cf7mcb168
      appId: wx41ae6a71bb9e10d0
      appSecret: 61fed55059ea3b838bf428dce9f88e07
      mchID: 1522007251
      subMchID:
      certLocalPath: classpath:/spring/pay/weiXinGJHApiClient_cert.p12
      certPassword: 1361997202
      useThreadToDoReport: true